### ISSUE TITLE
PHP 8.0 generates white image

### ISSUE THREAD

**Issue by tomasnorre** [erikaheidi/dynacover#12]
Hi.

There are no PHP requirements defined in the `composer.json` so I tried it out with PHP 8.0.
The result was that my cover image was just white. Nothing else. 

I see no errors, so I don't know yet what the problem can be. 

I have created this issue for visibility, in case others will run into this. 

I'll take a look at this when I find some more time. 

Thanks for this really cool little "tool".

**Comment by erikaheidi** [comment]
Thank you for flagging this issue, Tomas! I recently had some issues with GD/freetype support, I am working on a Docker image to facilitate setting up dependencies because it can really be a PITA on some servers. Then we can experiment with 8.0 and figure what's missing.

**Comment by tomasnorre** [comment]
Let me know if I can support in any way.

**Comment by tomasnorre** [comment]
Super, I never got to look more into this. Happy someone did :)
