### ISSUE TITLE
php dynacover twitter - Command "twitter" not found

### ISSUE THREAD

**Issue by tomasnorre** [erikaheidi/dynacover#3]
Hi, 

It looks to me like the command suggested in section 5 with `twitter` is incorrect or not implemented yet.
https://github.com/erikaheidi/dynacover#5-choose-a-template-and-preview-your-cover

I get following `Command "twitter" not found`

**Comment by tomasnorre** [comment]
From looking at the Code and the Help command. It looks like `twitter generate` is switched around compared to the other commands. But the `generate twitter` isn't working either. 

![image](https://user-images.githubusercontent.com/1212481/120900850-8d3cb900-c637-11eb-8333-ec4bf966201b.png)

I cannot say what is off. But looks like it's the place to dig a little more into.

**Comment by erikaheidi** [comment]
Thank you for catching the issue, it was a mistake in the README. Updated now! I inverted the thing ahha, it's `dynacover generate twitter` :)

**Comment by tomasnorre** [comment]
For me, it didn't work yesterday switching them around perhaps I had a typo in it. 

Thanks for correcting it. Can confirm that it works.
