### ISSUE TITLE
Suggestion: Random GitHub Sponsor

### ISSUE THREAD

**Issue by tomasnorre** [erikaheidi/dynacover#6]
I would like to suggest having the GitHub Sponsor picked Randomly, as I read it now, they are not random. 

The ones displayed at mine isn't even in order, it's my two first and my latest, and they don't get update when updating the image. So looks like there is no random implemented yet, also not from reading the code.

**Comment by tomasnorre** [comment]
I know the solution isn't that pretty, but quite pracmatic and simple. 

File: `app/ImageSource/GhSponsorImageSource.php`

```diff
$featured = [];

+ shuffle($sponsors);

/** @var ApiModel $sponsor */
foreach ($sponsors as $sponsor) {
```

**Comment by erikaheidi** [comment]
its OK! I also use `shuffle` for mine, but I forgot to include it when refactored. Thank you for the PR!
